server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    include /etc/nginx/redirects-nginx.conf;

    error_page 404 /404.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(webp|svg|woff2?|png|jpg)$ {
        expires 30d;
    }
}
