location = /2026/04/15/camisa-de-brim-personalizada/ { return 301 /produtos/camisa-de-brim/; }
location = /2026/04/15/camisa-de-brim-personalizada { return 301 /produtos/camisa-de-brim/; }
location = /2026/04/15/calca-de-brim-profissional/ { return 301 /produtos/calca-de-brim/; }
location = /2026/04/15/calca-de-brim-profissional { return 301 /produtos/calca-de-brim/; }
location = /2026/05/04/calca-de-brim-profissional-2/ { return 301 /produtos/calca-de-brim/; }
location = /2026/05/04/calca-de-brim-profissional-2 { return 301 /produtos/calca-de-brim/; }
location = /2026/07/22/calca-brim-com-elastico/ { return 301 /produtos/calca-de-brim-com-elastico/; }
location = /2026/07/22/calca-brim-com-elastico { return 301 /produtos/calca-de-brim-com-elastico/; }
location = /2026/07/22/macacao-brim/ { return 301 /produtos/macacao-de-brim/; }
location = /2026/07/22/macacao-brim { return 301 /produtos/macacao-de-brim/; }
location = /2026/08/21/conjunto-laranja/ { return 301 /produtos/conjunto-laranja/; }
location = /2026/08/21/conjunto-laranja { return 301 /produtos/conjunto-laranja/; }
location = /2026/08/20/jaleco-oxford/ { return 301 /produtos/jaleco-oxford/; }
location = /2026/08/20/jaleco-oxford { return 301 /produtos/jaleco-oxford/; }
location = /2026/06/23/jaleco-branco/ { return 301 /produtos/jaleco-branco/; }
location = /2026/06/23/jaleco-branco { return 301 /produtos/jaleco-branco/; }
location = /2026/08/21/jaleco-copeira/ { return 301 /produtos/jaleco-copeira/; }
location = /2026/08/21/jaleco-copeira { return 301 /produtos/jaleco-copeira/; }
location = /2026/07/22/avental-oxford/ { return 301 /produtos/avental-oxford/; }
location = /2026/07/22/avental-oxford { return 301 /produtos/avental-oxford/; }
location = /2026/07/22/jaqueta-nylon-masculina/ { return 301 /produtos/jaqueta-nylon-masculina/; }
location = /2026/07/22/jaqueta-nylon-masculina { return 301 /produtos/jaqueta-nylon-masculina/; }
location = /2026/08/20/jaqueta-feminina-3/ { return 301 /produtos/jaqueta-nylon-feminina/; }
location = /2026/08/20/jaqueta-feminina-3 { return 301 /produtos/jaqueta-nylon-feminina/; }
location = /2026/07/22/jaqueta-nylon-puffer/ { return 301 /produtos/jaqueta-puffer/; }
location = /2026/07/22/jaqueta-nylon-puffer { return 301 /produtos/jaqueta-puffer/; }
location = /2026/07/22/jaqueta-em-tecido-masculina/ { return 301 /produtos/jaqueta-tecido-masculina/; }
location = /2026/07/22/jaqueta-em-tecido-masculina { return 301 /produtos/jaqueta-tecido-masculina/; }
location = /2026/08/21/pulover-de-la-decote-v/ { return 301 /produtos/pulover-de-la-decote-v/; }
location = /2026/08/21/pulover-de-la-decote-v { return 301 /produtos/pulover-de-la-decote-v/; }
location = /2026/08/21/colete-feminino/ { return 301 /produtos/colete-feminino/; }
location = /2026/08/21/colete-feminino { return 301 /produtos/colete-feminino/; }
location = /category/hospitalar/ { return 301 /segmentos/hospitalar/; }
location = /category/hospitalar { return 301 /segmentos/hospitalar/; }
location = /category/alimenticio/ { return 301 /segmentos/alimenticio/; }
location = /category/alimenticio { return 301 /segmentos/alimenticio/; }
location = /category/industrial/ { return 301 /segmentos/industrial/; }
location = /category/industrial { return 301 /segmentos/industrial/; }
location = /category/construcao-civil/ { return 301 /segmentos/construcao-civil/; }
location = /category/construcao-civil { return 301 /segmentos/construcao-civil/; }
location = /category/transporte/ { return 301 /segmentos/transporte/; }
location = /category/transporte { return 301 /segmentos/transporte/; }
location = /category/seguranca/ { return 301 /segmentos/seguranca/; }
location = /category/seguranca { return 301 /segmentos/seguranca/; }
location = /category/uncategorized/ { return 301 /produtos/; }
location = /category/uncategorized { return 301 /produtos/; }
